package org.mvoks.datatransfer;

import org.glassfish.hk2.api.ServiceLocator;
import org.glassfish.hk2.utilities.ServiceLocatorUtilities;

/**
 * Assembling project:
 * <pre>
 *  mvm clear
 *  mvn install
 *  In IDEA press <b>"Build/Rebuild Project"</b>
 *  mvn install
 * </pre>
 * Check file: <b>target/classes/META-INF/hk2-localor/default</b><br/>
 * There should be something similar to this:
 * <pre>
 *
 * #
 * # Generated by hk2-metadata-generator
 * #
 *
 * [org.mvoks.datatransfer.DataTransferApplication]S
 *
 * [org.mvoks.datatransfer.config.yaml.YamlService]S
 * </pre>
 */
public class StartApplication {


    public static void main(String[] args) {
        final ServiceLocator serviceLocator = ServiceLocatorUtilities.createAndPopulateServiceLocator();
        final DataTransferApplication dataTransferApplication = serviceLocator.getService(DataTransferApplication.class);
        dataTransferApplication.perform();
    }
}